Preprocessing initial
BoevaLab/CanSig pull request #45
Opened 2022-05-27 12:58 UTC by FlorianBarkmann

This PR adds the preprocessing module to CanSig.

2022-05-27 13:43 UTC, pawel-czyz commented on .flake8
> +ignore = E712, W503, E203, C901
Sorry to say that, but turning C901 off is a no-go if we want to maintain reasonable code quality :/

2022-05-27 14:04 UTC, FlorianBarkmann commented on .flake8
> +ignore = E712, W503, E203, C901
Hmmm, it complained about DataRecorder._sanitize_adata which really isn't that complex, especially compared to other functions.

2022-05-27 14:04 UTC, pawel-czyz requested changes
Thanks Florian, this PR required a lot of effort to do – thanks for taking the responsibility! :slightly_smiling_face: 

However, I think we should refactor the code before merging. The rationale is that in the current shape this code will be difficult to maintain and if we don't refactor it now, we'll probably never find motivation to do it.

As this is a lot of code, maybe we could do a _team_ mini-hackathon aimed at refactoring this? (I'll be available after June 20th).

2022-05-27 14:05 UTC, FlorianBarkmann commented on .flake8
> +ignore = E712, W503, E203, C901
I guess it counts the number of for loops and if statements

2022-05-27 14:05 UTC, FlorianBarkmann commented on requirements.txt
> +infercnvpy
For preprocessing we do

2022-05-27 14:45 UTC, pawel-czyz commented on .flake8
> +ignore = E712, W503, E203, C901
In that case, I'd suggest turning it off just for that method by adding the `# noqa: C901` comment :slightly_smiling_face:

2022-05-27 14:59 UTC, FlorianBarkmann commented on .flake8
> +ignore = E712, W503, E203, C901
Sounds good! I didn't know that was an option;)

2022-05-27 15:28 UTC, FlorianBarkmann commented on cansig/_preprocessing/_infercnv.py
> +    if (missing_columns := _EXPECTED_COLUMNS - set(gene_order.columns)) != set():
If not, would work but I think there is benefit to being explicit in your if statements.

2022-05-31 17:10 UTC, FlorianBarkmann commented on cansig/_preprocessing/plotting.py
> +    :param adata: Anndata object
Thanks,  I missed that one. For the rest it should be google style.

2022-05-31 17:11 UTC, FlorianBarkmann commented on cansig/_preprocessing/main.py
> +    normalize_config = NormalizedConfig()
Good Catch!

2022-05-31 18:19 UTC, FlorianBarkmann commented on cansig/_preprocessing/main.py
> +def preprocessing(
I agree but I feel like that is less user-friendly.

2022-05-31 18:33 UTC, merged